#!/usr/bin/env python3
"""
generate_rule_docs.py — render docs/validation-rules.md from the rule registry.

Rule documentation that is maintained by hand drifts from the rules it
describes. This generates the reference page from the registered ``Rule``
objects instead, and ``--check`` fails CI when the committed page is stale.

Usage:
    python .github/scripts/generate_rule_docs.py           # write the page
    python .github/scripts/generate_rule_docs.py --check   # drift gate
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from rules.base import Rule
from rules.registry import discover_rules

DOCS_PATH = Path("docs") / "validation-rules.md"

_SCOPE_LABEL = {
    "changed-files": "Every changed file",
    "agent-folder": "Each touched agent folder",
    "kit-folder": "Each touched starter-kit folder",
    "repo": "Whole repository",
}


def render(rules: list[Rule]) -> str:
    lines = [
        "<!-- Generated by .github/scripts/generate_rule_docs.py — do not edit by hand. -->",
        "",
        "# Validation rules",
        "",
        "Automated checks that run on every pull request touching `agents/` or",
        "`starter-kits/`. Each rule reports with its ID, so a failure comment",
        "points straight at the section below.",
        "",
        "Two escape hatches exist, and neither is a way to skip review:",
        "",
        "- **Waivers** (`.github/policy/waivers.yaml`) — a reviewed exception for one",
        "  rule on one path. Requires a CODEOWNER approver and an expiry date; an",
        "  expired waiver fails the build.",
        "- **Ratchet baseline** (`.github/policy/baseline.json`) — violations that",
        "  predate a rule. Reported as warnings so legacy content keeps building,",
        "  while any new violation of the same rule still blocks.",
        "",
        "## Rule index",
        "",
        "| Rule | Summary | Applies to | Severity |",
        "| --- | --- | --- | --- |",
    ]

    for rule in rules:
        scope = _SCOPE_LABEL.get(rule.scope.value, rule.scope.value)
        lines.append(
            f"| [{rule.id}](#{rule.id.lower()}) | {rule.summary} | {scope} | "
            f"{rule.severity.value} |"
        )

    lines.append("")

    for rule in rules:
        lines.extend([
            f"## {rule.id}",
            "",
            rule.summary,
            "",
            f"- **Applies to:** {_SCOPE_LABEL.get(rule.scope.value, rule.scope.value)}",
            f"- **Severity:** {rule.severity.value}",
        ])
        if rule.tags:
            lines.append(f"- **Tags:** {', '.join(rule.tags)}")
        lines.extend([
            "",
            "**How to fix**",
            "",
            rule.remediation,
            "",
        ])
        if rule.docs:
            lines.extend([f"Further reading: `{rule.docs}`", ""])

    lines.extend([
        "## Other validation families",
        "",
        "The `STR-*`, `SCH-*`, `DOC-*`, and remaining `POL-*` checks live in",
        "`.github/scripts/catalog_validation/`. They run alongside this modular",
        "engine from the shared PR validation runner. See `docs/validation-rules.csv`",
        "for the complete source-backed inventory.",
        "",
    ])

    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repo-root", default=".")
    parser.add_argument("--check", action="store_true",
                        help="Fail if the committed page differs from the generated one.")
    args = parser.parse_args()

    repo = Path(args.repo_root).resolve()
    target = repo / DOCS_PATH
    content = render(discover_rules())

    if args.check:
        current = target.read_text(encoding="utf-8") if target.exists() else ""
        if current != content:
            print(
                f"{DOCS_PATH} is out of date with the rule registry.\n"
                f"Regenerate it with:\n"
                f"    python .github/scripts/generate_rule_docs.py",
                file=sys.stderr,
            )
            return 1
        print(f"{DOCS_PATH} is up to date.")
        return 0

    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(content, encoding="utf-8")
    print(f"Wrote {DOCS_PATH}.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
